# Generated by Django 5.0.6 on 2024-06-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_bankrukpt',
            field=models.BooleanField(default=False),
        ),
    ]
