# Generated by Django 5.0.6 on 2024-06-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction_is_bankrukpt'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bankrupt', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_bankrukpt',
        ),
    ]
